// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"uuid"
)

type Session struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt string    `json:"expires_at"`
	CreatedAt string    `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	FirstName    *string   `json:"first_name"`
	LastName     *string   `json:"last_name"`
	PasswordHash string    `json:"-"`
	Email        string    `json:"email"`
	IsAdmin      bool      `json:"is_admin"`
	IsActive     bool      `json:"is_active"`
	LastLogin    *string   `json:"last_login"`
	CreatedAt    string    `json:"created_at"`
	UpdatedAt    string    `json:"updated_at"`
	DeletedAt    *string   `json:"deleted_at"`
}
