// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateUserStmt, err = db.PrepareContext(ctx, activateUser); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateUser: %w", err)
	}
	if q.cleanExpiredSessionsStmt, err = db.PrepareContext(ctx, cleanExpiredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query CleanExpiredSessions: %w", err)
	}
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deactivateUserStmt, err = db.PrepareContext(ctx, deactivateUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeactivateUser: %w", err)
	}
	if q.deleteAllUserSessionsStmt, err = db.PrepareContext(ctx, deleteAllUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllUserSessions: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.hardDeleteUserStmt, err = db.PrepareContext(ctx, hardDeleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query HardDeleteUser: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.softDeleteUserStmt, err = db.PrepareContext(ctx, softDeleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteUser: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserLastLoginStmt, err = db.PrepareContext(ctx, updateUserLastLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserLastLogin: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateUserStmt != nil {
		if cerr := q.activateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateUserStmt: %w", cerr)
		}
	}
	if q.cleanExpiredSessionsStmt != nil {
		if cerr := q.cleanExpiredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanExpiredSessionsStmt: %w", cerr)
		}
	}
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deactivateUserStmt != nil {
		if cerr := q.deactivateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deactivateUserStmt: %w", cerr)
		}
	}
	if q.deleteAllUserSessionsStmt != nil {
		if cerr := q.deleteAllUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllUserSessionsStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.hardDeleteUserStmt != nil {
		if cerr := q.hardDeleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hardDeleteUserStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.softDeleteUserStmt != nil {
		if cerr := q.softDeleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteUserStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserLastLoginStmt != nil {
		if cerr := q.updateUserLastLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserLastLoginStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	activateUserStmt          *sql.Stmt
	cleanExpiredSessionsStmt  *sql.Stmt
	countUsersStmt            *sql.Stmt
	createSessionStmt         *sql.Stmt
	createUserStmt            *sql.Stmt
	deactivateUserStmt        *sql.Stmt
	deleteAllUserSessionsStmt *sql.Stmt
	deleteSessionStmt         *sql.Stmt
	getSessionStmt            *sql.Stmt
	getUserStmt               *sql.Stmt
	getUserByEmailStmt        *sql.Stmt
	getUserByUsernameStmt     *sql.Stmt
	hardDeleteUserStmt        *sql.Stmt
	listUsersStmt             *sql.Stmt
	softDeleteUserStmt        *sql.Stmt
	updateUserStmt            *sql.Stmt
	updateUserLastLoginStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		activateUserStmt:          q.activateUserStmt,
		cleanExpiredSessionsStmt:  q.cleanExpiredSessionsStmt,
		countUsersStmt:            q.countUsersStmt,
		createSessionStmt:         q.createSessionStmt,
		createUserStmt:            q.createUserStmt,
		deactivateUserStmt:        q.deactivateUserStmt,
		deleteAllUserSessionsStmt: q.deleteAllUserSessionsStmt,
		deleteSessionStmt:         q.deleteSessionStmt,
		getSessionStmt:            q.getSessionStmt,
		getUserStmt:               q.getUserStmt,
		getUserByEmailStmt:        q.getUserByEmailStmt,
		getUserByUsernameStmt:     q.getUserByUsernameStmt,
		hardDeleteUserStmt:        q.hardDeleteUserStmt,
		listUsersStmt:             q.listUsersStmt,
		softDeleteUserStmt:        q.softDeleteUserStmt,
		updateUserStmt:            q.updateUserStmt,
		updateUserLastLoginStmt:   q.updateUserLastLoginStmt,
	}
}
