// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
;

DELETE FROM sessions
WHERE expires_at < datetime('now'
`

// Esto lo puedes correr en un ticker de Go cada 1 hora
func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanExpiredSessionsStmt, cleanExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash, user_id, ip_address, user_agent, expires_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateSessionParams struct {
	TokenHash []byte  `json:"token_hash"`
	UserID    []byte  `json:"user_id"`
	IpAddress *string `json:"ip_address"`
	UserAgent *string `json:"user_agent"`
	ExpiresAt string  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions
WHERE user_id =
`

// Útil cuando un usuario cambia su password o es desactivado
func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID []byte) error {
	_, err := q.exec(ctx, q.deleteAllUserSessionsStmt, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT 
    token_hash, user_id, ip_address, user_agent, expires_at, s.created_at, id, username, first_name, last_name, password_hash, email, is_admin, is_active, last_login, u.created_at, updated_at, deleted_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token_hash = ? AND s.expires_at > datetime('now')
LIMIT 1
`

type GetSessionRow struct {
	TokenHash    []byte  `json:"token_hash"`
	UserID       []byte  `json:"user_id"`
	IpAddress    *string `json:"ip_address"`
	UserAgent    *string `json:"user_agent"`
	ExpiresAt    string  `json:"expires_at"`
	CreatedAt    string  `json:"created_at"`
	ID           []byte  `json:"id"`
	Username     string  `json:"username"`
	FirstName    *string `json:"first_name"`
	LastName     *string `json:"last_name"`
	PasswordHash string  `json:"password_hash"`
	Email        string  `json:"email"`
	IsAdmin      bool    `json:"is_admin"`
	IsActive     bool    `json:"is_active"`
	LastLogin    *string `json:"last_login"`
	CreatedAt_2  string  `json:"created_at_2"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Email,
		&i.IsAdmin,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt_2,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
