// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Soporte API",
            "url": "http://www.tu-sitio.com/support",
            "email": "soporte@tu-dominio.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/containers": {
            "get": {
                "description": "Get all running containers managed by quadlets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "List containers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_core_api_serializer.ListContainer"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}": {
            "get": {
                "description": "Get a container by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Get container by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_core_api_serializer.GetContainer"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}/logs": {
            "get": {
                "description": "Get logs from a container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Get container logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logs stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}/restart": {
            "post": {
                "description": "Restart a container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Restart container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}/start": {
            "post": {
                "description": "Start a container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Start container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}/stats": {
            "get": {
                "description": "Get resource usage statistics for a container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Get container stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ContainerStats"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/containers/{name}/stop": {
            "post": {
                "description": "Stop a container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Stop container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/libpod/{path}": {
            "get": {
                "description": "Proxies requests to the Podman API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "libpod"
                ],
                "summary": "Proxy to Podman API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API path",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/quadlets": {
            "get": {
                "description": "Get all quadlet files",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "List quadlets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_core_api_serializer.ListQuadlets"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new quadlet file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "Create quadlet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quadlet name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quadlet data",
                        "name": "quadlet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/quadlets/{name}": {
            "get": {
                "description": "Get a quadlet file by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "Get quadlet by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quadlet name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Replace or create a quadlet file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "Replace or create quadlet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quadlet name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quadlet data",
                        "name": "quadlet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a quadlet file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "Delete quadlet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quadlet name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing quadlet file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quadlets"
                ],
                "summary": "Update quadlet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quadlet name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Override file",
                        "name": "override",
                        "in": "query"
                    },
                    {
                        "description": "Quadlet data",
                        "name": "quadlet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "define.ContainerSize": {
            "type": "object",
            "properties": {
                "rootFsSize": {
                    "type": "integer"
                },
                "rwSize": {
                    "type": "integer"
                }
            }
        },
        "entities.ListContainer": {
            "type": "object",
            "properties": {
                "Id": {
                    "description": "The unique identifier for the container",
                    "type": "string"
                },
                "autoRemove": {
                    "description": "AutoRemove",
                    "type": "boolean"
                },
                "cidfile": {
                    "description": "CIDFile specified at creation time.",
                    "type": "string"
                },
                "command": {
                    "description": "Container command",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created": {
                    "description": "Container creation time",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Human-readable container creation time.",
                    "type": "string"
                },
                "exitCode": {
                    "description": "If container has exited, the return code from the command",
                    "type": "integer",
                    "format": "int32"
                },
                "exited": {
                    "description": "If container has exited/stopped",
                    "type": "boolean"
                },
                "exitedAt": {
                    "description": "Time container exited",
                    "type": "integer",
                    "format": "int64"
                },
                "exposedPorts": {
                    "description": "ExposedPorts contains the ports that are exposed but not forwarded,\nsee Ports for forwarded ports.\nThe key is the port number and the string slice contains the protocols,\ni.e. \"tcp\", \"udp\" and \"sctp\".",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "image": {
                    "description": "Container image",
                    "type": "string"
                },
                "imageID": {
                    "description": "Container image ID",
                    "type": "string"
                },
                "isInfra": {
                    "description": "If this container is a Pod infra container",
                    "type": "boolean"
                },
                "labels": {
                    "description": "Labels for container",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mounts": {
                    "description": "User volume mounts",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "names": {
                    "description": "The names assigned to the container",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "namespaces": {
                    "description": "Namespaces the container belongs to.  Requires the\nnamespace boolean to be true",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.ListContainerNamespaces"
                        }
                    ]
                },
                "networks": {
                    "description": "The network names assigned to the container",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pid": {
                    "description": "The process id of the container",
                    "type": "integer"
                },
                "pod": {
                    "description": "If the container is part of Pod, the Pod ID. Requires the pod\nboolean to be set",
                    "type": "string"
                },
                "podName": {
                    "description": "If the container is part of Pod, the Pod name. Requires the pod\nboolean to be set",
                    "type": "string"
                },
                "ports": {
                    "description": "Port mappings",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.PortMapping"
                    }
                },
                "restarts": {
                    "description": "Restarts is how many times the container was restarted by its\nrestart policy. This is NOT incremented by normal container restarts\n(only by restart policy).",
                    "type": "integer"
                },
                "size": {
                    "description": "Size of the container rootfs.  Requires the size boolean to be true",
                    "allOf": [
                        {
                            "$ref": "#/definitions/define.ContainerSize"
                        }
                    ]
                },
                "startedAt": {
                    "description": "Time when container started",
                    "type": "integer",
                    "format": "int64"
                },
                "state": {
                    "description": "State of container",
                    "type": "string"
                },
                "status": {
                    "description": "Status is a human-readable approximation of a duration for json output",
                    "type": "string"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_core_api_serializer.GetContainer": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ContainerEntity"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_core_api_serializer.ListContainer": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ContainerEntity"
                    }
                }
            }
        },
        "github_com_moleship-org_moleship_internal_core_api_serializer.ListQuadlets": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.QuadletFile"
                    }
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry": {
            "type": "object",
            "properties": {
                "major": {
                    "type": "integer"
                },
                "minor": {
                    "type": "integer"
                },
                "op": {
                    "description": "\"Read\", \"Write\", \"Sync\", \"Async\", \"Total\"",
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.BlkioStats": {
            "type": "object",
            "properties": {
                "io_merged_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_queue_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_service_bytes_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_service_time_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_serviced_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_time_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "io_wait_time_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                },
                "sectors_recursive": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStatEntry"
                    }
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.CPUStats": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.CPUUsage"
                },
                "online_cpus": {
                    "type": "integer"
                },
                "system_cpu_usage": {
                    "type": "integer"
                },
                "throttling_data": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ThrottlingData"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.CPUUsage": {
            "type": "object",
            "properties": {
                "total_usage": {
                    "type": "integer"
                },
                "usage_in_kernelmode": {
                    "type": "integer"
                },
                "usage_in_usermode": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.ContainerEntity": {
            "type": "object",
            "properties": {
                "container": {
                    "$ref": "#/definitions/entities.ListContainer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "description": "active, inactive, failed, etc.",
                    "type": "string"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.ContainerOptions": {
            "type": "object",
            "properties": {
                "add_capability": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "annotation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "args": {
                    "type": "string"
                },
                "auto_update": {
                    "type": "string"
                },
                "container_name": {
                    "type": "string"
                },
                "drop_capability": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "entrypoint": {
                    "type": "string"
                },
                "environment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "environment_file": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exec": {
                    "type": "string"
                },
                "expose_host_port": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "health_cmd": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "label": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "network": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pod": {
                    "type": "string"
                },
                "publish_port": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "removable": {
                    "type": "boolean"
                },
                "secret": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "security_label_disable": {
                    "type": "boolean"
                },
                "timezone": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "userns": {
                    "type": "string"
                },
                "volume": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.ContainerStats": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "string"
                },
                "blkio_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.BlkioStats"
                },
                "cpu_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.CPUStats"
                },
                "memory_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.MemoryStats"
                },
                "name": {
                    "type": "string"
                },
                "networks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.Network"
                    }
                },
                "num_procs": {
                    "type": "integer"
                },
                "pids_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.PidsStats"
                },
                "precpu_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.CPUStats"
                },
                "preread": {
                    "type": "string"
                },
                "read": {
                    "type": "string"
                },
                "storage_stats": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.StorageStats"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.InstallOptions": {
            "type": "object",
            "properties": {
                "required_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wanted_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.MemoryStats": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "usage": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.Network": {
            "type": "object",
            "properties": {
                "rx_bytes": {
                    "type": "integer"
                },
                "rx_dropped": {
                    "type": "integer"
                },
                "rx_errors": {
                    "type": "integer"
                },
                "rx_packets": {
                    "type": "integer"
                },
                "tx_bytes": {
                    "type": "integer"
                },
                "tx_dropped": {
                    "type": "integer"
                },
                "tx_errors": {
                    "type": "integer"
                },
                "tx_packets": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.PidsStats": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.QuadletFile": {
            "type": "object",
            "properties": {
                "container": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ContainerOptions"
                },
                "install": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.InstallOptions"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "service": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.ServiceOptions"
                },
                "unit": {
                    "$ref": "#/definitions/github_com_moleship-org_moleship_internal_domain_model.UnitOptions"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.ServiceOptions": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exec_start_post": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exec_start_pre": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "restart": {
                    "type": "string"
                },
                "timeout_start_sec": {
                    "type": "string"
                },
                "timeout_stop_sec": {
                    "type": "string"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.StorageStats": {
            "type": "object",
            "properties": {
                "read_count": {
                    "type": "integer"
                },
                "read_size": {
                    "type": "integer"
                },
                "write_count": {
                    "type": "integer"
                },
                "write_size": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.ThrottlingData": {
            "type": "object",
            "properties": {
                "periods": {
                    "type": "integer"
                },
                "throttled_periods": {
                    "type": "integer"
                },
                "throttled_time": {
                    "type": "integer"
                }
            }
        },
        "github_com_moleship-org_moleship_internal_domain_model.UnitOptions": {
            "type": "object",
            "properties": {
                "after": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "before": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "requires": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "types.ListContainerNamespaces": {
            "type": "object",
            "properties": {
                "Cgroup": {
                    "description": "Cgroup namespace",
                    "type": "string"
                },
                "Ipc": {
                    "description": "IPC namespace",
                    "type": "string"
                },
                "Mnt": {
                    "description": "Mount namespace",
                    "type": "string"
                },
                "Net": {
                    "description": "Network namespace",
                    "type": "string"
                },
                "Pidns": {
                    "description": "PID namespace",
                    "type": "string"
                },
                "User": {
                    "description": "User namespace",
                    "type": "string"
                },
                "Uts": {
                    "description": "UTS namespace",
                    "type": "string"
                }
            }
        },
        "types.PortMapping": {
            "type": "object",
            "properties": {
                "container_port": {
                    "description": "ContainerPort is the port number that will be exposed from the\ncontainer.\nMandatory.",
                    "type": "integer"
                },
                "host_ip": {
                    "description": "HostIP is the IP that we will bind to on the host.\nIf unset, assumed to be 0.0.0.0 (all interfaces).",
                    "type": "string"
                },
                "host_port": {
                    "description": "HostPort is the port number that will be forwarded from the host into\nthe container.\nIf omitted, a random port on the host (guaranteed to be over 1024)\nwill be assigned.",
                    "type": "integer"
                },
                "protocol": {
                    "description": "Protocol is the protocol forward.\nMust be either \"tcp\", \"udp\", and \"sctp\", or some combination of these\nseparated by commas.\nIf unset, assumed to be TCP.",
                    "type": "string"
                },
                "range": {
                    "description": "Range is the number of ports that will be forwarded, starting at\nHostPort and ContainerPort and counting up.\nThis is 1-indexed, so 1 is assumed to be a single port (only the\nHostport:Containerport mapping will be added), 2 is two ports (both\nHostport:Containerport and Hostport+1:Containerport+1), etc.\nIf unset, assumed to be 1 (a single port).\nBoth hostport + range and containerport + range must be less than\n65536.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Moleship API",
	Description:      "Esta es una descripción detallada de lo que hace mi API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
