// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
;

DELETE FROM sessions
WHERE expires_at < datetime('now'
`

// Esto lo puedes correr en un ticker de Go cada 1 hora
func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanExpiredSessionsStmt, cleanExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash, user_id, ip_address, user_agent, expires_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateSessionParams struct {
	TokenHash []byte  `json:"token_hash"`
	UserID    []byte  `json:"user_id"`
	IpAddress *string `json:"ip_address"`
	UserAgent *string `json:"user_agent"`
	ExpiresAt string  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions
WHERE user_id =
`

// Útil cuando un usuario cambia su password o es desactivado
func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID []byte) error {
	_, err := q.exec(ctx, q.deleteAllUserSessionsStmt, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
    token_hash, user_id, ip_address, user_agent, expires_at, created_at
FROM sessions s
WHERE s.token_hash = ? AND s.expires_at > datetime('now')
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT 
    token_hash, user_id, ip_address, user_agent, expires_at, created_at
FROM sessions
WHERE user_id = ? AND expires_at > datetime('now')
`

func (q *Queries) GetUserSessions(ctx context.Context, userID []byte) ([]Session, error) {
	rows, err := q.query(ctx, q.getUserSessionsStmt, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
